<?php
if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_5b286c2297436',
	'title' => 'Page Sections',
	'fields' => array(
		array(
			'key' => 'field_5b2ef8a53f890',
			'label' => 'Sections',
			'name' => 'sections',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'5b32f0ffd7089' => array(
					'key' => '5b32f0ffd7089',
					'name' => 'banner',
					'label' => 'Banner',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b32f12cd708a',
							'label' => 'Section Layout',
							'name' => 'section_layout',
							'type' => 'flexible_content',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layouts' => array(
								'5b2effd4365ad' => array(
									'key' => '5b2effd4365ad',
									'name' => 'image_slider',
									'label' => 'Image Slider',
									'display' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_5b32f12cd708b',
											'label' => 'Image Slider',
											'name' => 'image_slider',
											'type' => 'flexible_content',
											'instructions' => 'The images and captions for the image slider that will appear at the top of the page.',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'layouts' => array(
												'5b2efa394e86a' => array(
													'key' => '5b2efa394e86a',
													'name' => 'image',
													'label' => 'Image',
													'display' => 'row',
													'sub_fields' => array(
														array(
															'key' => 'field_5b32f12cd708c',
															'label' => 'Image',
															'name' => 'image',
															'type' => 'image',
															'instructions' => 'The image that will be displayed',
															'required' => 0,
															'conditional_logic' => 0,
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'return_format' => 'array',
															'preview_size' => 'medium',
															'library' => 'all',
															'min_width' => 700,
															'min_height' => '',
															'min_size' => '',
															'max_width' => 2000,
															'max_height' => '',
															'max_size' => '',
															'mime_types' => '',
														),
														array(
															'key' => 'field_5b32f12cd708d',
															'label' => 'Title',
															'name' => 'title',
															'type' => 'text',
															'instructions' => 'The title for the image.',
															'required' => 0,
															'conditional_logic' => 0,
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'default_value' => '',
															'placeholder' => '',
															'prepend' => '',
															'append' => '',
															'maxlength' => '',
														),
														array(
															'key' => 'field_5b32f12cd708e',
															'label' => 'Caption',
															'name' => 'caption',
															'type' => 'textarea',
															'instructions' => 'The text area of the image.',
															'required' => 0,
															'conditional_logic' => 0,
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'default_value' => '',
															'placeholder' => '',
															'maxlength' => '',
															'rows' => '',
															'new_lines' => '',
														),
														array(
															'key' => 'field_5b32f12cd708f',
															'label' => 'Text Alignment',
															'name' => 'text_alignment',
															'type' => 'select',
															'instructions' => '',
															'required' => 0,
															'conditional_logic' => 0,
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'choices' => array(
																'left' => 'Left',
																'center' => 'Center',
																'right' => 'Right',
															),
															'default_value' => array(
																0 => 'left',
															),
															'allow_null' => 0,
															'multiple' => 0,
															'ui' => 0,
															'ajax' => 0,
															'return_format' => 'value',
															'placeholder' => '',
														),
														array(
															'key' => 'field_5b32f12cd7090',
															'label' => 'Include Button',
															'name' => 'include_button',
															'type' => 'true_false',
															'instructions' => '',
															'required' => 0,
															'conditional_logic' => 0,
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'message' => '',
															'default_value' => 0,
															'ui' => 1,
															'ui_on_text' => '',
															'ui_off_text' => '',
														),
														array(
															'key' => 'field_5b32f12cd7091',
															'label' => 'Button',
															'name' => 'button',
															'type' => 'clone',
															'instructions' => '',
															'required' => 0,
															'conditional_logic' => array(
																array(
																	array(
																		'field' => 'field_5b32f12cd7090',
																		'operator' => '==',
																		'value' => '1',
																	),
																),
															),
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'clone' => array(
																0 => 'field_5b2c64f2f92e0',
															),
															'display' => 'group',
															'layout' => 'row',
															'prefix_label' => 0,
															'prefix_name' => 0,
														),
													),
													'min' => '',
													'max' => '',
												),
											),
											'button_label' => 'Add Image',
											'min' => '',
											'max' => '',
										),
									),
									'min' => '',
									'max' => '',
								),
							),
							'button_label' => 'Add Layout',
							'min' => '',
							'max' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5b2efded5697a' => array(
					'key' => '5b2efded5697a',
					'name' => 'image',
					'label' => 'Image',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b2effb975022',
							'label' => 'Section Layout',
							'name' => 'section_layout',
							'type' => 'flexible_content',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layouts' => array(
								'5b2effd4365ad' => array(
									'key' => '5b2effd4365ad',
									'name' => 'image_slider',
									'label' => 'Image Slider',
									'display' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_5b286c3578321',
											'label' => 'Image Slider',
											'name' => 'image_slider',
											'type' => 'flexible_content',
											'instructions' => 'The images and captions for the image slider that will appear at the top of the page.',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'layouts' => array(
												'5b2efa394e86a' => array(
													'key' => '5b2efa394e86a',
													'name' => 'image',
													'label' => 'Image',
													'display' => 'row',
													'sub_fields' => array(
														array(
															'key' => 'field_5b2efa394e86b',
															'label' => 'Image',
															'name' => 'image',
															'type' => 'image',
															'instructions' => 'The image that will be displayed',
															'required' => 0,
															'conditional_logic' => 0,
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'return_format' => 'array',
															'preview_size' => 'medium',
															'library' => 'all',
															'min_width' => 700,
															'min_height' => '',
															'min_size' => '',
															'max_width' => 2000,
															'max_height' => '',
															'max_size' => '',
															'mime_types' => '',
														),
														array(
															'key' => 'field_5b2efa394e86c',
															'label' => 'Title',
															'name' => 'title',
															'type' => 'text',
															'instructions' => 'The title for the image.',
															'required' => 0,
															'conditional_logic' => 0,
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'default_value' => '',
															'placeholder' => '',
															'prepend' => '',
															'append' => '',
															'maxlength' => '',
														),
														array(
															'key' => 'field_5b2efa394e86d',
															'label' => 'Caption',
															'name' => 'caption',
															'type' => 'textarea',
															'instructions' => 'The text area of the image.',
															'required' => 0,
															'conditional_logic' => 0,
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'default_value' => '',
															'placeholder' => '',
															'maxlength' => '',
															'rows' => '',
															'new_lines' => '',
														),
														array(
															'key' => 'field_5b2efa394e86e',
															'label' => 'Text Alignment',
															'name' => 'text_alignment',
															'type' => 'select',
															'instructions' => '',
															'required' => 0,
															'conditional_logic' => 0,
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'choices' => array(
																'left' => 'Left',
																'center' => 'Center',
																'right' => 'Right',
															),
															'default_value' => array(
																0 => 'left',
															),
															'allow_null' => 0,
															'multiple' => 0,
															'ui' => 0,
															'ajax' => 0,
															'return_format' => 'value',
															'placeholder' => '',
														),
														array(
															'key' => 'field_5b2efa394e86f',
															'label' => 'Include Button',
															'name' => 'include_button',
															'type' => 'true_false',
															'instructions' => '',
															'required' => 0,
															'conditional_logic' => 0,
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'message' => '',
															'default_value' => 0,
															'ui' => 1,
															'ui_on_text' => '',
															'ui_off_text' => '',
														),
														array(
															'key' => 'field_5b2efa394e870',
															'label' => 'Button',
															'name' => 'button',
															'type' => 'clone',
															'instructions' => '',
															'required' => 0,
															'conditional_logic' => array(
																array(
																	array(
																		'field' => 'field_5b2efa394e86f',
																		'operator' => '==',
																		'value' => '1',
																	),
																),
															),
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'clone' => array(
																0 => 'field_5b2c64f2f92e0',
															),
															'display' => 'group',
															'layout' => 'row',
															'prefix_label' => 0,
															'prefix_name' => 0,
														),
													),
													'min' => '',
													'max' => '',
												),
											),
											'button_label' => 'Add Image',
											'min' => '',
											'max' => '',
										),
									),
									'min' => '',
									'max' => '',
								),
								'5b2f00fe18df3' => array(
									'key' => '5b2f00fe18df3',
									'name' => 'image',
									'label' => 'Image',
									'display' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_5b2f037b90d3a',
											'label' => 'Image',
											'name' => 'image',
											'type' => 'clone',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'clone' => array(
												0 => 'field_5b32f12cd708c',
											),
											'display' => 'seamless',
											'layout' => 'block',
											'prefix_label' => 0,
											'prefix_name' => 0,
										),
									),
									'min' => '',
									'max' => '',
								),
							),
							'button_label' => 'Add Layout',
							'min' => '',
							'max' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5b2efe24f7944' => array(
					'key' => '5b2efe24f7944',
					'name' => 'card',
					'label' => 'Card',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b2f025490d36',
							'label' => 'Section Layout',
							'name' => 'section_layout',
							'type' => 'flexible_content',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layouts' => array(
								'5b2f025fc56b3' => array(
									'key' => '5b2f025fc56b3',
									'name' => 'standard',
									'label' => 'Standard',
									'display' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_5b29d64f1fe50',
											'label' => 'Standard',
											'name' => 'standard',
											'type' => 'repeater',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'collapsed' => '',
											'min' => 0,
											'max' => 0,
											'layout' => 'table',
											'button_label' => 'Add Card',
											'sub_fields' => array(
												array(
													'key' => 'field_5b29d66f1fe51',
													'label' => 'Include Image',
													'name' => 'include_image',
													'type' => 'true_false',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'message' => '',
													'default_value' => 0,
													'ui' => 0,
													'ui_on_text' => '',
													'ui_off_text' => '',
												),
												array(
													'key' => 'field_5b29d6a21fe52',
													'label' => 'Image',
													'name' => 'image',
													'type' => 'image',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => array(
														array(
															array(
																'field' => 'field_5b29d66f1fe51',
																'operator' => '==',
																'value' => '1',
															),
														),
													),
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'return_format' => 'array',
													'preview_size' => 'medium',
													'library' => 'all',
													'min_width' => '',
													'min_height' => '',
													'min_size' => '',
													'max_width' => '',
													'max_height' => '',
													'max_size' => '',
													'mime_types' => '',
												),
												array(
													'key' => 'field_5b2ef0504a015',
													'label' => 'Title',
													'name' => 'title',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key' => 'field_5b2ef18fd33f4',
													'label' => 'Main Text',
													'name' => 'main_text',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => 150,
												),
												array(
													'key' => 'field_5b3006d502010',
													'label' => 'Card Color',
													'name' => 'card_color',
													'type' => 'clone',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'clone' => array(
														0 => 'field_5b3005d3a35cd',
													),
													'display' => 'seamless',
													'layout' => 'block',
													'prefix_label' => 0,
													'prefix_name' => 0,
												),
											),
										),
									),
									'min' => '',
									'max' => '',
								),
							),
							'button_label' => 'Add Layout',
							'min' => '',
							'max' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5b2efe30f7945' => array(
					'key' => '5b2efe30f7945',
					'name' => 'slider',
					'label' => 'Slider',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b2f026c90d37',
							'label' => 'Section Layout',
							'name' => 'section_layout',
							'type' => 'flexible_content',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layouts' => array(
								'5b2f025fc56b3' => array(
									'key' => '5b2f025fc56b3',
									'name' => 'standard',
									'label' => 'Standard',
									'display' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_5b46af42fc064',
											'label' => 'Standard',
											'name' => 'standard',
											'type' => 'flexible_content',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'layouts' => array(
												'5b46b164eef3d' => array(
													'key' => '5b46b164eef3d',
													'name' => 'image_row',
													'label' => 'Image Row',
													'display' => 'block',
													'sub_fields' => array(
														array(
															'key' => 'field_5b57dd3931aa0',
															'label' => 'Slides',
															'name' => 'slides',
															'type' => 'repeater',
															'instructions' => '',
															'required' => 0,
															'conditional_logic' => 0,
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'collapsed' => '',
															'min' => 0,
															'max' => 0,
															'layout' => 'table',
															'button_label' => 'Add Slide',
															'sub_fields' => array(
																array(
																	'key' => 'field_5b57dd7731aa1',
																	'label' => 'Image',
																	'name' => 'image',
																	'type' => 'image',
																	'instructions' => '',
																	'required' => 0,
																	'conditional_logic' => 0,
																	'wrapper' => array(
																		'width' => '',
																		'class' => '',
																		'id' => '',
																	),
																	'return_format' => 'url',
																	'preview_size' => 'medium',
																	'library' => 'all',
																	'min_width' => '',
																	'min_height' => '',
																	'min_size' => '',
																	'max_width' => '',
																	'max_height' => '',
																	'max_size' => '',
																	'mime_types' => '',
																),
																array(
																	'key' => 'field_5b57dd9131aa2',
																	'label' => 'Text',
																	'name' => 'text',
																	'type' => 'text',
																	'instructions' => '',
																	'required' => 0,
																	'conditional_logic' => 0,
																	'wrapper' => array(
																		'width' => '',
																		'class' => '',
																		'id' => '',
																	),
																	'default_value' => '',
																	'placeholder' => '',
																	'prepend' => '',
																	'append' => '',
																	'maxlength' => '',
																),
															),
														),
													),
													'min' => '',
													'max' => '',
												),
											),
											'button_label' => 'Add Image Row',
											'min' => '',
											'max' => '',
										),
									),
									'min' => '',
									'max' => '',
								),
							),
							'button_label' => 'Add Layout',
							'min' => '',
							'max' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5b2efeaef7946' => array(
					'key' => '5b2efeaef7946',
					'name' => 'text',
					'label' => 'Text',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b2f027e90d38',
							'label' => 'Section Layout',
							'name' => 'section_layout',
							'type' => 'flexible_content',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layouts' => array(
								'5b2f025fc56b3' => array(
									'key' => '5b2f025fc56b3',
									'name' => 'standard',
									'label' => 'Standard',
									'display' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_5b55034d974d0',
											'label' => 'Standard',
											'name' => 'standard',
											'type' => 'flexible_content',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'layouts' => array(
												'5b5503697d018' => array(
													'key' => '5b5503697d018',
													'name' => 'standard',
													'label' => 'Standard',
													'display' => 'block',
													'sub_fields' => array(
														array(
															'key' => 'field_5b54febcf219d',
															'label' => 'Has Image',
															'name' => 'has_image',
															'type' => 'true_false',
															'instructions' => '',
															'required' => 1,
															'conditional_logic' => 0,
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'message' => '',
															'default_value' => 0,
															'ui' => 0,
															'ui_on_text' => '',
															'ui_off_text' => '',
														),
														array(
															'key' => 'field_5b54ff3bf219f',
															'label' => 'Image',
															'name' => 'image',
															'type' => 'clone',
															'instructions' => '',
															'required' => 0,
															'conditional_logic' => 0,
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'clone' => array(
																0 => 'field_5b32f12cd708c',
															),
															'display' => 'seamless',
															'layout' => 'block',
															'prefix_label' => 0,
															'prefix_name' => 0,
														),
														array(
															'key' => 'field_5b54ffc3425d1',
															'label' => 'Image Align',
															'name' => 'image_align',
															'type' => 'select',
															'instructions' => '',
															'required' => 0,
															'conditional_logic' => array(
																array(
																	array(
																		'field' => 'field_5b54febcf219d',
																		'operator' => '==',
																		'value' => '1',
																	),
																),
															),
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'choices' => array(
																'left' => 'Left',
																'center' => 'Center',
																'right' => 'Right',
															),
															'default_value' => array(
															),
															'allow_null' => 0,
															'multiple' => 0,
															'ui' => 0,
															'ajax' => 0,
															'return_format' => 'value',
															'placeholder' => '',
														),
														array(
															'key' => 'field_5b551a3bd92cf',
															'label' => 'Title',
															'name' => 'title',
															'type' => 'text',
															'instructions' => '',
															'required' => 0,
															'conditional_logic' => 0,
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'default_value' => '',
															'placeholder' => '',
															'prepend' => '',
															'append' => '',
															'maxlength' => '',
														),
														array(
															'key' => 'field_5b54ff58f21a0',
															'label' => 'Main Text',
															'name' => 'main_text',
															'type' => 'textarea',
															'instructions' => '',
															'required' => 0,
															'conditional_logic' => 0,
															'wrapper' => array(
																'width' => '',
																'class' => '',
																'id' => '',
															),
															'default_value' => '',
															'placeholder' => '',
															'maxlength' => '',
															'rows' => '',
															'new_lines' => '',
														),
													),
													'min' => '',
													'max' => '',
												),
											),
											'button_label' => 'Add Row',
											'min' => '',
											'max' => '',
										),
									),
									'min' => '',
									'max' => '',
								),
							),
							'button_label' => 'Add Layout',
							'min' => '',
							'max' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5b6340caab98d' => array(
					'key' => '5b6340caab98d',
					'name' => 'events',
					'label' => 'Events',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b6340f8ab990',
							'label' => 'Section Layout',
							'name' => 'section_layout',
							'type' => 'flexible_content',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layouts' => array(
								'5b63413ba0169' => array(
									'key' => '5b63413ba0169',
									'name' => 'standard',
									'label' => 'Standard',
									'display' => 'block',
									'sub_fields' => array(
									),
									'min' => '',
									'max' => '',
								),
								'5b8dafe38092a' => array(
									'key' => '5b8dafe38092a',
									'name' => 'calendar',
									'label' => 'Calendar',
									'display' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_5b8dafeb8092b',
											'label' => 'Calendar',
											'name' => 'calendar',
											'type' => 'select',
											'instructions' => '',
											'required' => 1,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'choices' => array(
												'monthly' => 'Monthly',
												'weekly' => 'Weekly',
												'agenda' => 'Agenda',
												'posterboard' => 'Posterboard',
											),
											'default_value' => array(
												0 => 'monthly',
											),
											'allow_null' => 0,
											'multiple' => 0,
											'ui' => 1,
											'ajax' => 0,
											'return_format' => 'value',
											'placeholder' => '',
										),
									),
									'min' => '',
									'max' => '',
								),
							),
							'button_label' => 'Add Layout',
							'min' => '',
							'max' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5b65c6c2f1668' => array(
					'key' => '5b65c6c2f1668',
					'name' => 'block',
					'label' => 'Block',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b65c6edf1669',
							'label' => 'Section Layout',
							'name' => 'section_layout',
							'type' => 'flexible_content',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layouts' => array(
								'5b65c728cc1ca' => array(
									'key' => '5b65c728cc1ca',
									'name' => 'standard',
									'label' => 'Standard',
									'display' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_5b65c738f166a',
											'label' => 'Standard',
											'name' => '',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
									),
									'min' => '',
									'max' => '',
								),
								'5b65c9550d81f' => array(
									'key' => '5b65c9550d81f',
									'name' => 'background_image',
									'label' => 'With Background Image',
									'display' => 'block',
									'sub_fields' => array(
									),
									'min' => '',
									'max' => '',
								),
								'5b65c9840d820' => array(
									'key' => '5b65c9840d820',
									'name' => 'background_color',
									'label' => 'With Background Color',
									'display' => 'block',
									'sub_fields' => array(
									),
									'min' => '',
									'max' => '',
								),
							),
							'button_label' => 'Add Layout',
							'min' => '',
							'max' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5b65c6c2f1667' => array(
					'key' => '5b65c6c2f1667',
					'name' => 'box',
					'label' => 'Box',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b65c7f20d81b',
							'label' => 'Section Layout',
							'name' => 'section_layout',
							'type' => 'flexible_content',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layouts' => array(
								'5b65c80f9fa79' => array(
									'key' => '5b65c80f9fa79',
									'name' => 'standard',
									'label' => 'Standard',
									'display' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_5b65c8cd0d81e',
											'label' => 'Standard',
											'name' => 'standard',
											'type' => 'text',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'default_value' => '',
											'placeholder' => '',
											'prepend' => '',
											'append' => '',
											'maxlength' => '',
										),
									),
									'min' => '',
									'max' => '',
								),
								'5b65c9a50d821' => array(
									'key' => '5b65c9a50d821',
									'name' => 'hover_image',
									'label' => 'Hover Image',
									'display' => 'block',
									'sub_fields' => array(
										array(
											'key' => 'field_5bafa8042e482',
											'label' => 'Hover Image',
											'name' => 'hover_image',
											'type' => 'repeater',
											'instructions' => '',
											'required' => 0,
											'conditional_logic' => 0,
											'wrapper' => array(
												'width' => '',
												'class' => '',
												'id' => '',
											),
											'collapsed' => '',
											'min' => 0,
											'max' => 0,
											'layout' => 'table',
											'button_label' => '',
											'sub_fields' => array(
												array(
													'key' => 'field_5bafa621c3278',
													'label' => 'Image',
													'name' => 'image',
													'type' => 'image',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'return_format' => 'array',
													'preview_size' => 'medium',
													'library' => 'all',
													'min_width' => 250,
													'min_height' => 250,
													'min_size' => '',
													'max_width' => 1000,
													'max_height' => 1000,
													'max_size' => '',
													'mime_types' => '',
												),
												array(
													'key' => 'field_5bafa69fc327a',
													'label' => 'Title',
													'name' => 'title',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key' => 'field_5bafa8332e483',
													'label' => 'Link Text',
													'name' => 'link_text',
													'type' => 'text',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
													'prepend' => '',
													'append' => '',
													'maxlength' => '',
												),
												array(
													'key' => 'field_5bafa671c3279',
													'label' => 'Link',
													'name' => 'link',
													'type' => 'url',
													'instructions' => '',
													'required' => 0,
													'conditional_logic' => 0,
													'wrapper' => array(
														'width' => '',
														'class' => '',
														'id' => '',
													),
													'default_value' => '',
													'placeholder' => '',
												),
											),
										),
									),
									'min' => '',
									'max' => '',
								),
								'5b65c9c80d822' => array(
									'key' => '5b65c9c80d822',
									'name' => 'image',
									'label' => 'With Image',
									'display' => 'block',
									'sub_fields' => array(
									),
									'min' => '',
									'max' => '',
								),
							),
							'button_label' => 'Add Layout',
							'min' => '',
							'max' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'5baf8deacb8f7' => array(
					'key' => '5baf8deacb8f7',
					'name' => 'blog',
					'label' => 'Blog',
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5baf8dfacb8f8',
							'label' => 'Section Layout',
							'name' => 'section_layout',
							'type' => 'flexible_content',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'layouts' => array(
								'5baf8e057466a' => array(
									'key' => '5baf8e057466a',
									'name' => 'home',
									'label' => 'Home',
									'display' => 'block',
									'sub_fields' => array(
									),
									'min' => '',
									'max' => '',
								),
							),
							'button_label' => 'Add Row',
							'min' => '',
							'max' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
			),
			'button_label' => 'Add Section',
			'min' => '',
			'max' => '',
		),
		array(
			'key' => 'field_5b2c64c2f92df',
			'label' => 'Page Components',
			'name' => 'page_components',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
				array(
					'key' => 'field_5b2c64f2f92e0',
					'label' => 'Button',
					'name' => 'button',
					'type' => 'group',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'layout' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5b2c6540f92e1',
							'label' => 'Button Color',
							'name' => 'button_color',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'light-green' => 'Light Green',
								'light-brown' => 'Light Brown',
								'light-blue' => 'Light Blue',
								'dark-blue' => 'Dark Blue',
								'orange' => 'Orange',
								'green' => 'Green',
								'purple' => 'Purple',
								'success' => 'Success',
								'info' => 'Info',
								'warning' => 'Warning',
								'danger' => 'Danger',
							),
							'default_value' => array(
								0 => 'default',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_5b2c6581f92e2',
							'label' => 'Button Text',
							'name' => 'button_text',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5b2c65aef92e3',
							'label' => 'Button Link',
							'name' => 'button_link',
							'type' => 'url',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
						),
					),
				),
				array(
					'key' => 'field_5b3005d3a35cd',
					'label' => 'Color',
					'name' => 'color',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'light-green' => 'Light Green',
						'light-brown' => 'Light Brown',
						'light-blue' => 'Light Blue',
						'dark-blue' => 'Dark Blue',
						'orange' => 'Orange',
						'green' => 'Green',
						'purple' => 'Purple',
						'success' => 'Success',
						'info' => 'Info',
						'warning' => 'Warning',
						'danger' => 'Danger',
						'white' => 'White',
					),
					'default_value' => array(
						0 => 'default',
					),
					'allow_null' => 0,
					'multiple' => 0,
					'ui' => 0,
					'ajax' => 0,
					'return_format' => 'value',
					'placeholder' => '',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'default',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/left-sidebar.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/no-sidebar.php',
			),
		),
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'page-templates/right-sidebar.php',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => array(
		0 => 'the_content',
		1 => 'excerpt',
		2 => 'custom_fields',
		3 => 'discussion',
		4 => 'comments',
		5 => 'revisions',
		6 => 'slug',
		7 => 'author',
		8 => 'format',
		9 => 'featured_image',
		10 => 'send-trackbacks',
	),
	'active' => 1,
	'description' => '',
));

endif;